In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
sns.set_style("darkgrid")

In [4]:
customers = pd.read_csv("olist_customers_dataset.csv")

REVIEWING AND CLEANING EACH INDIVIDUAL DATASET

CUSTOMER DATASET

In [6]:
customers = customers.rename({"customer_zip_code_prefix" : "customer_zip_code"},axis = 1)

In [7]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
customers.info()

ORDER_ITEMS DATASET

In [8]:
order_items = pd.read_csv("olist_order_items_dataset.csv")

In [9]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
order_items.info()

In [10]:
order_payments = pd.read_csv("olist_order_payments_dataset.csv")

In [ ]:
order_payments.head()

In [ ]:
order_payments.info()

In [11]:
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")

In [12]:
order_reviews.head(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [13]:
order_reviews = order_reviews.drop(columns = ["review_comment_title","review_comment_message","review_creation_date"])

In [ ]:
order_reviews.info()

In [14]:
order = pd.read_csv("olist_orders_dataset.csv")

In [ ]:
order.head()

In [ ]:
order.info()

In [15]:
products = pd.read_csv("olist_products_dataset.csv")

In [ ]:

products.head()

In [ ]:
products.info()

In [16]:
sellers = pd.read_csv("olist_sellers_dataset.csv")

In [ ]:
sellers.head()

In [ ]:
sellers.info()

In [17]:
product_category = pd.read_csv("product_category_name_translation.csv")

In [ ]:
product_category.head()

In [ ]:
product_category.info()

MERGING DATASETS

In [18]:
#joining products and product category
product_merged = pd.merge(products,product_category, on = 'product_category_name', how = 'inner')

In [ ]:
product_merged.head()

In [ ]:
product_merged.info()

In [19]:
product_merged['Product_Volume'] = product_merged['product_length_cm'] * product_merged['product_height_cm'] * product_merged['product_width_cm']

In [20]:
product_merged = product_merged.drop(columns = ['product_length_cm','product_height_cm','product_width_cm'])

In [21]:
product_merged = product_merged.drop(columns = ['product_category_name'])

In [ ]:
product_merged.info()

MERGING ORDER_ITEM AND PRODUCT_MERGED TABLE ON PRODUCT ID

In [22]:
Order_product_merged = pd.merge(order_items,product_merged, on = 'product_id', how = 'inner')

In [ ]:
Order_product_merged.info()

MERGING ORDER_PRODUCT_MERGED WITH ORDERS TABLE ON ORDER ID

In [23]:
Order_Product_merged_1 = pd.merge(Order_product_merged,order, on = 'order_id', how = 'inner')

In [ ]:
Order_Product_merged_1.info()

MERGING ORDER_PRODUCT_MERGED_1 WITH ORDER PAYMENTS TABLE ON ORDER ID

In [24]:

Order_Product_merged_2 = pd.merge(Order_Product_merged_1,order_payments, on = 'order_id', how = 'inner')

In [25]:
Order_Product_merged_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115878 entries, 0 to 115877
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115878 non-null  object
 1   order_item_id                  115878 non-null  int64
 2   product_id                     115878 non-null  object
 3   seller_id                      115878 non-null  object
 4   shipping_limit_date            115878 non-null  object
 5   price                          115878 non-null  float64
 6   freight_value                  115878 non-null  float64
 7   product_name_lenght            115878 non-null  float64
 8   product_description_lenght     115878 non-null  float64
 9   product_photos_qty             115878 non-null  float64
 10  product_weight_g               115877 non-null  float64
 11  product_category_name_english  115878 non-null  object
 12  Product_Volume                 115877 non-null  float64
 13  customer_id                    115878 non-null  object
 14  order_status                   115878 non-null  object
 15  order_purchase_timestamp       115878 non-null  object
 16  order_approved_at              115864 non-null  object
 17  order_delivered_carrier_date   114673 non-null  object
 18  order_delivered_customer_date  113383 non-null  object
 19  order_estimated_delivery_date  115878 non-null  object
 20  payment_sequential             115878 non-null  int64
 21  payment_type                   115878 non-null  object
 22  payment_installments           115878 non-null  int64
 23  payment_value                  115878 non-null  float64
dtypes: float64(8), int64(3), object(13)
memory usage: 21.2+ MB

In [26]:
Order_Product_merged_3 = pd.merge(Order_Product_merged_2,order_reviews, on = 'order_id', how = 'left')

In [ ]:
Order_Product_merged_3.info()

JOINING ORDER MERGED DATA WITH CUSTOMERS DATA

In [27]:
Order_Product_Customer = pd.merge(Order_Product_merged_3,customers, on = 'customer_id', how = 'inner')

In [ ]:
Order_Product_Customer.info()

JOINING PRODUCT_CUSTOMER MERGED DATA WITH SELLER DATA

In [48]:
Final_df1 = pd.merge(Order_Product_Customer,sellers, on = 'seller_id', how = 'inner')

In [ ]:
Final_df1.info()

In [93]:
Final_df1.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_category_name_english,Product_Volume,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_answer_timestamp,customer_unique_id,customer_zip_code,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,58.0,598.0,4.0,650.0,cool_stuff,3528.0,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,1,credit_card,2,72.19,97ca439bc427b48bc1cd7177abe71365,5.0,2017-09-22 10:57:03,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,27277,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,56.0,239.0,2.0,30000.0,pet_shop,60000.0,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00,1,credit_card,3,259.83,7b07bacd811c4117b742569b04ce3580,4.0,2017-05-15 11:34:13,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP,3471,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,59.0,695.0,2.0,3050.0,furniture_decor,14157.0,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00,1,credit_card,5,216.87,0c5b33dea94867d1ac402749e5438e8b,5.0,2018-01-23 16:06:31,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG,37564,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,42.0,480.0,1.0,200.0,perfumery,2400.0,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00,1,credit_card,2,25.78,f4028d019cb58564807486a6aaf33817,4.0,2018-08-15 16:39:01,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP,14403,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,59.0,409.0,1.0,3750.0,garden_tools,42000.0,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00,1,credit_card,3,218.04,940144190dcba6351888cafa43f3a3a5,5.0,2017-03-03 10:54:59,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP,87900,loanda,PR

In [94]:
Df_Data = Final_df1.drop(columns = ['shipping_limit_date','product_name_lenght','product_description_lenght','review_id','order_approved_at','order_delivered_carrier_date','payment_sequential'])

In [95]:
Df_Data = Df_Data.drop(columns = ['customer_unique_id'])

In [ ]:
#Final_df[Final_df["order_id"] == '00143d0f86d6fbd9f9b38ab440ac16f5']

In [51]:
Df_Data.head()

,order_id,order_item_id,product_id,seller_id,price,freight_value,product_photos_qty,product_weight_g,product_category_name_english,Product_Volume,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_installments,payment_value,review_score,review_answer_timestamp,customer_unique_id,customer_zip_code,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,4.0,650.0,cool_stuff,3528.0,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-20 23:43:48,2017-09-29 00:00:00,credit_card,2,72.19,5.0,2017-09-22 10:57:03,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,27277,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,2.0,30000.0,pet_shop,60000.0,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-05-12 16:04:24,2017-05-15 00:00:00,credit_card,3,259.83,4.0,2017-05-15 11:34:13,eb28e67c4c0b83846050ddfb8a35d051,15775,santa fe do sul,SP,3471,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,2.0,3050.0,furniture_decor,14157.0,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-22 13:19:16,2018-02-05 00:00:00,credit_card,5,216.87,5.0,2018-01-23 16:06:31,3818d81c6709e39d06b2738a8d3a2474,35661,para de minas,MG,37564,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,1.0,200.0,perfumery,2400.0,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-14 13:32:39,2018-08-20 00:00:00,credit_card,2,25.78,4.0,2018-08-15 16:39:01,af861d436cfc08b2c2ddefd0ba074622,12952,atibaia,SP,14403,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,1.0,3750.0,garden_tools,42000.0,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-03-01 16:42:31,2017-03-17 00:00:00,credit_card,3,218.04,5.0,2017-03-03 10:54:59,64b576fb70d441e8f1b2d7d446e483c5,13226,varzea paulista,SP,87900,loanda,PR

In [96]:
Df_Data = Df_Data.rename(columns = {'product_category_name_english':'product_category','seller_zip_code_prefix':'seller_zip_code'})

In [97]:
Df_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116573 entries, 0 to 116572
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       116573 non-null  object
 1   order_item_id                  116573 non-null  int64
 2   product_id                     116573 non-null  object
 3   seller_id                      116573 non-null  object
 4   price                          116573 non-null  float64
 5   freight_value                  116573 non-null  float64
 6   product_photos_qty             116573 non-null  float64
 7   product_weight_g               116572 non-null  float64
 8   product_category               116573 non-null  object
 9   Product_Volume                 116572 non-null  float64
 10  customer_id                    116573 non-null  object
 11  order_status                   116573 non-null  object
 12  order_purchase_timestamp       116573 non-null  object
 13  order_delivered_customer_date  114058 non-null  object
 14  order_estimated_delivery_date  116573 non-null  object
 15  payment_type                   116573 non-null  object
 16  payment_installments           116573 non-null  int64
 17  payment_value                  116573 non-null  float64
 18  review_score                   115609 non-null  float64
 19  review_answer_timestamp        115609 non-null  object
 20  customer_zip_code              116573 non-null  int64
 21  customer_city                  116573 non-null  object
 22  customer_state                 116573 non-null  object
 23  seller_zip_code                116573 non-null  int64
 24  seller_city                    116573 non-null  object
 25  seller_state                   116573 non-null  object
dtypes: float64(7), int64(4), object(15)
memory usage: 23.1+ MB

In [98]:
#Converting datatype of customer_zip_code and seller_zip_code to object type
Df_Data[['seller_zip_code','customer_zip_code']] = Df_Data[['seller_zip_code','customer_zip_code']].astype(str)

In [33]:
Df_Data.describe()

,order_item_id,price,freight_value,product_photos_qty,product_weight_g,Product_Volume,payment_installments,payment_value,review_score,customer_zip_code,seller_zip_code_prefix
count,116573.000000,116573.000000,116573.000000,116573.000000,116572.000000,116572.000000,116573.000000,116573.000000,115609.000000,116573.000000,116573.00000
mean,1.196967,120.748834,20.062348,2.205039,2115.507815,15413.789049,2.949431,172.909723,4.034409,35052.879869,24505.06088
std,0.701372,183.850442,15.845812,1.717451,3783.609183,23667.722464,2.783651,267.628697,1.385584,29817.839020,27625.32404
min,1.000000,0.850000,0.000000,1.000000,0.000000,168.000000,0.000000,0.000000,1.000000,1003.000000,1001.00000
25%,1.000000,39.900000,13.080000,1.000000,300.000000,2873.000000,1.000000,61.000000,4.000000,11310.000000,6429.00000
50%,1.000000,74.900000,16.320000,1.000000,700.000000,6656.000000,2.000000,108.190000,5.000000,24315.000000,13690.00000
75%,1.000000,134.900000,21.220000,3.000000,1800.000000,18600.000000,4.000000,189.720000,5.000000,58600.000000,28495.00000
max,21.000000,6735.000000,409.680000,20.000000,40425.000000,296208.000000,24.000000,13664.080000,5.000000,99980.000000,99730.00000

In [99]:
#To get the unique value count of each variable
Df_Data.nunique()

order_id                         97255
order_item_id                       21
product_id                       32328
seller_id                         3033
price                             5899
freight_value                     6977
product_photos_qty                  19
product_weight_g                  2201
product_category                    71
Product_Volume                    4487
customer_id                      97255
order_status                         7
order_purchase_timestamp         96720
order_delivered_customer_date    94336
order_estimated_delivery_date      449
payment_type                         4
payment_installments                24
payment_value                    28765
review_score                         5
review_answer_timestamp          96163
customer_zip_code                14927
customer_city                     4095
customer_state                      27
seller_zip_code                   2211
seller_city                        604
seller_state                        23
dtype: int64

In [100]:
Df_Data.isna().sum()

order_id                            0
order_item_id                       0
product_id                          0
seller_id                           0
price                               0
freight_value                       0
product_photos_qty                  0
product_weight_g                    1
product_category                    0
Product_Volume                      1
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_delivered_customer_date    2515
order_estimated_delivery_date       0
payment_type                        0
payment_installments                0
payment_value                       0
review_score                      964
review_answer_timestamp           964
customer_zip_code                   0
customer_city                       0
customer_state                      0
seller_zip_code                     0
seller_city                         0
seller_state                        0
dtype: int64

Let's drop the missing values as the missing value data is very less

In [101]:
Df_Data = Df_Data.dropna(subset = ['order_delivered_customer_date','review_score','review_answer_timestamp','product_weight_g','Product_Volume'])

In [102]:
Df_Data.isna().sum()

order_id                         0
order_item_id                    0
product_id                       0
seller_id                        0
price                            0
freight_value                    0
product_photos_qty               0
product_weight_g                 0
product_category                 0
Product_Volume                   0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_delivered_customer_date    0
order_estimated_delivery_date    0
payment_type                     0
payment_installments             0
payment_value                    0
review_score                     0
review_answer_timestamp          0
customer_zip_code                0
customer_city                    0
customer_state                   0
seller_zip_code                  0
seller_city                      0
seller_state                     0
dtype: int64

In [121]:
Df_Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113208 entries, 0 to 116572
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113208 non-null  object
 1   order_item_id                  113208 non-null  int64
 2   product_id                     113208 non-null  object
 3   seller_id                      113208 non-null  object
 4   price                          113208 non-null  float64
 5   freight_value                  113208 non-null  float64
 6   product_photos_qty             113208 non-null  float64
 7   product_weight_g               113208 non-null  float64
 8   product_category               113208 non-null  object
 9   Product_Volume                 113208 non-null  float64
 10  customer_id                    113208 non-null  object
 11  order_status                   113208 non-null  object
 12  order_purchase_timestamp       113208 non-null  object
 13  order_delivered_customer_date  113208 non-null  object
 14  order_estimated_delivery_date  113208 non-null  object
 15  payment_type                   113208 non-null  object
 16  payment_installments           113208 non-null  int64
 17  payment_value                  113208 non-null  float64
 18  review_score                   113208 non-null  float64
 19  review_answer_timestamp        113208 non-null  object
 20  customer_zip_code              113208 non-null  object
 21  customer_city                  113208 non-null  object
 22  customer_state                 113208 non-null  object
 23  seller_zip_code                113208 non-null  object
 24  seller_city                    113208 non-null  object
 25  seller_state                   113208 non-null  object
 26  product_main_category          113208 non-null  object
 27  customer_id_short              113208 non-null  object
 28  seller_id_short                113208 non-null  object
 29  order_id_short                 113208 non-null  object
dtypes: float64(7), int64(2), object(21)
memory usage: 26.8+ MB

In [103]:
# Display all records in value counts without truncation
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
category_counts = Df_Data['product_category'].unique()
print(category_counts)

['cool_stuff' 'pet_shop' 'furniture_decor' 'perfumery' 'garden_tools'
 'housewares' 'telephony' 'health_beauty' 'books_technical'
 'fashion_bags_accessories' 'bed_bath_table' 'sports_leisure'
 'consoles_games' 'office_furniture' 'luggage_accessories' 'food'
 'agro_industry_and_commerce' 'electronics' 'computers_accessories'
 'construction_tools_construction' 'audio' 'baby'
 'construction_tools_lights' 'toys' 'stationery'
 'industry_commerce_and_business' 'watches_gifts' 'auto' 'home_appliances'
 'kitchen_dining_laundry_garden_furniture' 'air_conditioning'
 'home_confort' 'fixed_telephony' 'small_appliances_home_oven_and_coffee'
 'diapers_and_hygiene' 'signaling_and_security' 'musical_instruments'
 'small_appliances' 'costruction_tools_garden' 'art' 'home_construction'
 'books_general_interest' 'party_supplies' 'construction_tools_safety'
 'cine_photo' 'fashion_underwear_beach' 'fashion_male_clothing'
 'food_drink' 'drinks' 'furniture_living_room' 'market_place' 'music'
 'fashion_shoes' 'flowers' 'home_appliances_2' 'fashio_female_clothing'
 'computers' 'books_imported' 'christmas_supplies' 'furniture_bedroom'
 'home_comfort_2' 'dvds_blu_ray' 'cds_dvds_musicals'
 'arts_and_craftmanship' 'furniture_mattress_and_upholstery'
 'tablets_printing_image' 'costruction_tools_tools' 'fashion_sport'
 'la_cuisine' 'security_and_services' 'fashion_childrens_clothes']

In [104]:
category_map = {
    # 1. Consumer Electronics
    'electronics': 'Consumer Electronics',
    'audio': 'Consumer Electronics',
    'cine_photo': 'Consumer Electronics',
    'home_appliances': 'Consumer Electronics',
    'home_appliances_2': 'Consumer Electronics',
    'air_conditioning': 'Consumer Electronics',
    'small_appliances': 'Consumer Electronics',
    'small_appliances_home_oven_and_coffee': 'Consumer Electronics',

    # 2. Computers & Gadgets
    'computers': 'Computers & Gadgets',
    'computers_accessories': 'Computers & Gadgets',
    'tablets_printing_image': 'Computers & Gadgets',
    'telephony': 'Computers & Gadgets',
    'fixed_telephony': 'Computers & Gadgets',

    # 3. Home & Furniture
    'furniture_decor': 'Home & Furniture',
    'furniture_living_room': 'Home & Furniture',
    'furniture_bedroom': 'Home & Furniture',
    'furniture_mattress_and_upholstery': 'Home & Furniture',
    'kitchen_dining_laundry_garden_furniture': 'Home & Furniture',
    'bed_bath_table': 'Home & Furniture',
    'housewares': 'Home & Furniture',
    'home_confort': 'Home & Furniture',
    'home_comfort_2': 'Home & Furniture',
    'luggage_accessories': 'Home & Furniture',

    # 4. Fashion & Accessories
    'fashion_bags_accessories': 'Fashion & Accessories',
    'fashion_male_clothing': 'Fashion & Accessories',
    'fashio_female_clothing': 'Fashion & Accessories',
    'fashion_childrens_clothes': 'Fashion & Accessories',
    'fashion_underwear_beach': 'Fashion & Accessories',
    'fashion_shoes': 'Fashion & Accessories',
    'fashion_sport': 'Fashion & Accessories',
    'watches_gifts': 'Fashion & Accessories',

    # 5. Health, Beauty & Personal Care
    'health_beauty': 'Health, Beauty & Personal Care',
    'diapers_and_hygiene': 'Health, Beauty & Personal Care',
    'perfumery': 'Health, Beauty & Personal Care',
    'baby': 'Health, Beauty & Personal Care',

    # 6. Sports, Leisure & Toys
    'sports_leisure': 'Sports, Leisure & Toys',
    'toys': 'Sports, Leisure & Toys',
    'consoles_games': 'Sports, Leisure & Toys',
    'musical_instruments': 'Sports, Leisure & Toys',
    'cds_dvds_musicals': 'Sports, Leisure & Toys',
    'dvds_blu_ray': 'Sports, Leisure & Toys',
    'music': 'Sports, Leisure & Toys',

    # 7. Books, Art & Education
    'books_technical': 'Books, Art & Education',
    'books_general_interest': 'Books, Art & Education',
    'books_imported': 'Books, Art & Education',
    'art': 'Books, Art & Education',
    'arts_and_craftmanship': 'Books, Art & Education',
    'stationery': 'Books, Art & Education',

    # 8. Food, Drinks & Pet Supplies
    'food': 'Food, Drinks & Pet Supplies',
    'food_drink': 'Food, Drinks & Pet Supplies',
    'drinks': 'Food, Drinks & Pet Supplies',
    'pet_shop': 'Food, Drinks & Pet Supplies',
    'cool_stuff': 'Food, Drinks & Pet Supplies',
    'flowers': 'Food, Drinks & Pet Supplies',

    # 9. Home Improvement & Tools
    'garden_tools': 'Home Improvement & Tools',
    'construction_tools_construction': 'Home Improvement & Tools',
    'construction_tools_lights': 'Home Improvement & Tools',
    'construction_tools_safety': 'Home Improvement & Tools',
    'signaling_and_security': 'Home Improvement & Tools',
    'costruction_tools_garden': 'Home Improvement & Tools',
    'costruction_tools_tools': 'Home Improvement & Tools',
    'home_construction': 'Home Improvement & Tools',

    # 10. Marketplace, Party & Seasonal
    'market_place': 'Marketplace, Party & Seasonal',
    'party_supplies': 'Marketplace, Party & Seasonal',
    'christmas_supplies': 'Marketplace, Party & Seasonal',
    'la_cuisine': 'Marketplace, Party & Seasonal',

    # 11. Business, Office & Auto
    'office_furniture': 'Business, Office & Auto',
    'industry_commerce_and_business': 'Business, Office & Auto',
    'agro_industry_and_commerce': 'Business, Office & Auto',
    'auto': 'Business, Office & Auto',
    'security_and_services': 'Business, Office & Auto'
}

In [105]:
Df_Data['product_main_category'] = Df_Data['product_category'].map(category_map)

In [106]:
# rename customer_ids to simplified format
Df_Data["customer_id_short"] = pd.factorize(Df_Data['customer_id'])[0] + 1
Df_Data["customer_id_short"] = 'c'+ Df_Data["customer_id_short"].astype(str).str.zfill(3)

# rename seller_ids to simplified format
Df_Data["seller_id_short"] = pd.factorize(Df_Data['seller_id'])[0] + 1
Df_Data["seller_id_short"] = 's' + Df_Data["seller_id_short"].astype(str).str.zfill(3)

# rename order_ids to simplified format
Df_Data["order_id_short"] = pd.factorize(Df_Data['order_id'])[0] + 1
Df_Data["order_id_short"] = 'p' + Df_Data["order_id_short"].astype(str).str.zfill(3)

In [107]:
Df_Data.head()

,order_id,order_item_id,product_id,seller_id,price,freight_value,product_photos_qty,product_weight_g,product_category,Product_Volume,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,payment_type,payment_installments,payment_value,review_score,review_answer_timestamp,customer_zip_code,customer_city,customer_state,seller_zip_code,seller_city,seller_state,product_main_category,customer_id_short,seller_id_short,order_id_short
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,4.0,650.0,cool_stuff,3528.0,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-20 23:43:48,2017-09-29 00:00:00,credit_card,2,72.19,5.0,2017-09-22 10:57:03,28013,campos dos goytacazes,RJ,27277,volta redonda,SP,"Food, Drinks & Pet Supplies",c001,s001,p001
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,2.0,30000.0,pet_shop,60000.0,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-05-12 16:04:24,2017-05-15 00:00:00,credit_card,3,259.83,4.0,2017-05-15 11:34:13,15775,santa fe do sul,SP,3471,sao paulo,SP,"Food, Drinks & Pet Supplies",c002,s002,p002
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,2.0,3050.0,furniture_decor,14157.0,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-22 13:19:16,2018-02-05 00:00:00,credit_card,5,216.87,5.0,2018-01-23 16:06:31,35661,para de minas,MG,37564,borda da mata,MG,Home & Furniture,c003,s003,p003
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,1.0,200.0,perfumery,2400.0,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-14 13:32:39,2018-08-20 00:00:00,credit_card,2,25.78,4.0,2018-08-15 16:39:01,12952,atibaia,SP,14403,franca,SP,"Health, Beauty & Personal Care",c004,s004,p004
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,1.0,3750.0,garden_tools,42000.0,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-03-01 16:42:31,2017-03-17 00:00:00,credit_card,3,218.04,5.0,2017-03-03 10:54:59,13226,varzea paulista,SP,87900,loanda,PR,Home Improvement & Tools,c005,s005,p005

In [109]:
Df_Data['customer_zip_code'] = Df_Data['customer_zip_code'].astype(str)
Df_Data['seller_zip_code'] = Df_Data['seller_zip_code'].astype(str)

In [118]:
Df_Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113208 entries, 0 to 116572
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113208 non-null  object
 1   order_item_id                  113208 non-null  int64
 2   product_id                     113208 non-null  object
 3   seller_id                      113208 non-null  object
 4   price                          113208 non-null  float64
 5   freight_value                  113208 non-null  float64
 6   product_photos_qty             113208 non-null  float64
 7   product_weight_g               113208 non-null  float64
 8   product_category               113208 non-null  object
 9   Product_Volume                 113208 non-null  float64
 10  customer_id                    113208 non-null  object
 11  order_status                   113208 non-null  object
 12  order_purchase_timestamp       113208 non-null  object
 13  order_delivered_customer_date  113208 non-null  object
 14  order_estimated_delivery_date  113208 non-null  object
 15  payment_type                   113208 non-null  object
 16  payment_installments           113208 non-null  int64
 17  payment_value                  113208 non-null  float64
 18  review_score                   113208 non-null  float64
 19  review_answer_timestamp        113208 non-null  object
 20  customer_zip_code              113208 non-null  object
 21  customer_city                  113208 non-null  object
 22  customer_state                 113208 non-null  object
 23  seller_zip_code                113208 non-null  object
 24  seller_city                    113208 non-null  object
 25  seller_state                   113208 non-null  object
 26  product_main_category          113208 non-null  object
 27  customer_id_short              113208 non-null  object
 28  seller_id_short                113208 non-null  object
 29  order_id_short                 113208 non-null  object
dtypes: float64(7), int64(2), object(21)
memory usage: 26.8+ MB

In [116]:
#Save the final DataFrame to a file
Df_Data.to_csv("Ecommerce_Data.csv", index = False)

In [37]:
print(Df_Data['order_status'].value_counts())

order_status
delivered    113201
canceled          7
Name: count, dtype: int64

In [114]:
Df_Data['payment_type'].value_counts()

payment_type
credit_card    83535
boleto         22029
voucher         6022
debit_card      1622
Name: count, dtype: int64

In [120]:
Df_Data['review_score'].value_counts()

review_score
5.0    65153
4.0    21816
1.0    12865
3.0     9534
2.0     3840
Name: count, dtype: int64